### ISSUE TITLE
Failed to deploy  parse server exmaple v1.2.0 to aws

### ISSUE THREAD

**Issue by hawkit** [ParsePlatform/parse-server-example#101]
I have found we can't deploy v1.2.0 to aws .  And I get the log from 

>  /var/log/eb-activity.log

and find following error information

>  ../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
   #include <gssapi/gssapi.h>
                             ^
  compilation terminated.
  make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1

I have googled for hours  and finally I have solved this issue just to change the the kerberos version to  0.0.16 at package.json. 

`{
  "name": "parse-server-example",
  "version": "1.2.0",
  "description": "An example Parse API server using the parse-server module",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/ParsePlatform/parse-server-example"
  },
  "license": "MIT",
  "dependencies": {
    "express": "~4.2.x",
    "kerberos": "~0.0.16",
    "parse": "~1.6.12",
    "parse-server": "~2.1.4"
  },
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": ">=4.3"
  }
}
`

**It's very strange. After I restarted EBS, then I deploy a new version to EBS today, this error occurs again. **

**Comment by nickgerig** [comment]
I've had this same issue. Hardcoding the kerberos version didn't work.

**Comment by drew-gross** [comment]
Unfortunately we can't support AWS specific issues here. If you do find a solution, though, please post it so that others can benefit it.
