### ISSUE TITLE
Running a cloud function from express route

### ISSUE THREAD

**Issue by MobileAndyB** [ParsePlatform/parse-server-example#102]
Using the new parse server is there a way to call a function in the main.js file from the index.js? Example is to allow an endpoint for a third party so they can post a set of data without needed the application_id or any keys.

Old hosted parse.com allowed like this;
```
app.post('/test', function(req, res) {
    Parse.Cloud.run('functionname' data);
}
```
But I cannot get the routing to work in parse-server.

**Comment by gfosco** [comment]
It's possible, yeah, and should work, but you have to do something with the response.  Not clear what issue you're having here.  If you're still having trouble, please open a new issue with more details.
