### ISSUE TITLE
Kerberos dependency warning

### ISSUE THREAD

**Issue by amalo95** [ParsePlatform/parse-server-example#11]
On npm install I get this error. Mac OS X

`npm WARN mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.`

**Comment by spoek** [comment]
Same here!

**Comment by iulianvarzaru** [comment]
Run this command and it will fix this issue:

`sudo npm install kerberos --save`

**Comment by gfosco** [comment]
cc @jamesyu another item for the guide

**Comment by alirezariahi** [comment]
@iulianvrz 
Thanks! it's work!
