### ISSUE TITLE
Always getting a 403 when trying the example

### ISSUE THREAD

**Issue by adrianbrink** [ParsePlatform/parse-server-example#115]
Hi,

I've just cloned the example and I followed the instructions. However when running it on localhost I get a 403.

How do I specify the masterKey in my header?

Thank you.

**Comment by drew-gross** [comment]
Specify the master key on the command line or in your config file. If you get a 403 error, that probably means there was a typo in your master key or app ID.

**Comment by adrianbrink** [comment]
Fixed it :-) Thank you
