### ISSUE TITLE
I can't run my express app

### ISSUE THREAD

**Issue by pazalvin** [ParsePlatform/parse-server-example#12]
**here's the error:**
 node index.js

/parse-server/parse-server-example/node_modules/parse-server/node_modules/bindings/bindings.js:91
  throw err
  
 node index.js

/parse-server/parse-server-example/node_modules/parse-server/node_modules/bindings/bindings.js:91
  throw err
  ^

**Error: Could not locate the bindings file. Tried:**
 /parse-server/parse-server-example/node_modules/parse-server/node_modules/bcrypt/build/bcrypt_lib.node

**Comment by gfosco** [comment]
Did you run npm install successfully?

**Comment by pazalvin** [comment]
my npm gave me this 

npm WARN EPEERINVALID mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! path ../node-uuid/bin/uuid
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../node-uuid/bin/uuid' -> '/parse-server/parse-server-example/node_modules/.bin/uuid'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! path npm-debug.log.38c15850640860903cc05f623c8dd681
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.38c15850640860903cc05f623c8dd681' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /parse-server/parse-server-example/npm-debug.log

**Comment by pazalvin** [comment]
actually when you npm install the app theres is a no parse-server module there what i did is clone the the parse-server then npm install. but same error

/parse-server/parse-server-example/node_modules/parse-server/node_modules/bindings/bindings.js:91
throw err

node index.js

/parse-server/parse-server-example/node_modules/parse-server/node_modules/bindings/bindings.js:91
throw err
^
Error: Could not locate the bindings file. Tried:
/parse-server/parse-server-example/node_modules/parse-server/node_modules/bcrypt/build/bcrypt_lib.node

**Comment by gfosco** [comment]
Looks related to this issue here?  at least the original error did... https://github.com/ParsePlatform/parse-server/issues/77

What platform and version of node & python are you using?

**Comment by pazalvin** [comment]
will try the releted issue you gave to me 

btw this is my node version : v5.4.0, my enviroment: ubuntu 14.10

**Comment by pazalvin** [comment]
thanks @gfosco my app is working now :-)
