### ISSUE TITLE
ParseServer.createLiveQueryServer is not a function

### ISSUE THREAD

**Issue by bahmutov** [ParsePlatform/parse-server-example#125]
Running on Node 5.7 without any modifications, getting an error right away
```
$ node index.js 
DATABASE_URI not specified, falling back to localhost.
/parse-server-example/node_modules/parse-server/lib/index.js:335
            throw err;
            ^
TypeError: ParseServer.createLiveQueryServer is not a function
```

**Comment by zhouhao27** [comment]
Got the same problem.

**Comment by kbyatnal** [comment]
Have the same issue as well

**Comment by debianmaster** [comment]
same here!

**Comment by drew-gross** [comment]
This was caused by a change in Babel. We will be shipping parse-server version 2.2.2 today which will fix the problem. In the meantime, you should still be able to use version 2.2.0.
