### ISSUE TITLE
The data couldn’t be read because it isn’t in the correct format

### ISSUE THREAD

**Issue by hasrants** [ParsePlatform/parse-server-example#132]
I am running parse-server-example using parse-server 2.2.2. It is running on Heroku and MongoDB is on ObjectRocket.  When I use the parse API from parse.com and MongoDB running on ObjectRocket, app works as expected.  When I switch SERVER to "https://myapp.herokuapp.com" in swift and try to use parse-server then I get an error in any of my NetworkManager calls to parse api with "The data couldn't be read because it isn't in the correct format".

Not sure what details I can provide to help you help me.

In Heroku I have config vars for APP_ID, SERVER_URL, MONGOLAB_URI, MASTER_KEY, PARSE_MOUNT, CLIENT_KEY

in Swift I have: (value, value1, and my app are just place holders for this post right now)
let configuration = ParseClientConfiguration {
            $0.applicationId = "value"
            $0.clientKey = "value1"
            $0.server = "https://myapp.herokuapp.com/parse"
        }
        Parse.initializeWithConfiguration(configuration)

// example usage of parse 
     query.findObjectsInBackgroundWithBlock { (objects, error) -> Void in
            
            if let constError = error
            {
                //println("error fetching following")
                completionHandler(objects: nil, error: constError)
            }
            else
            {
                // println("success fetching following \(objects)")
                
                let postQuery = PFQuery(className: "Post")
                postQuery.whereKey("user", containedIn: objects!)
                postQuery.orderByDescending("createdAt")
                postQuery.limit = 25
                postQuery.skip = skipPosts
                postQuery.findObjectsInBackgroundWithBlock({ (objects, error) -> Void in
                    
                    completionHandler(objects: objects, error: error)
                    
                })
            }

Since parse.com is working this seems to confirm the API calls above are fine in terms of working and returning proper results. Since parse.com API works this also confirms MongoDB data migrated is intact from the migration.  This narrows is down slightly to Heroku and/or parse-server-example/parse-server but not sure what I should be looking for now.

Thank you

**Comment by hasrants** [comment]
Ok, it appears to be db connection issue.
Anyone see any issues with the following MongDB URI I am using (I have tried ssl=true and without it):

MONGOLAB_URI = mongodb://myusername:mypassword@iad1-c13-0.mongo.objectrocket.com:51078,iad1-c13-1.mongo.objectrocket.com:51078,iad1-c13-2.mongo.objectrocket.com:51078/myappname?ssl=true

{ [MongoError: connect ECONNREFUSED 172.99.86.10:51078]
2016-03-25T03:09:55.796772+00:00 app[web.1]:   name: 'MongoError',
2016-03-25T03:09:55.796775+00:00 app[web.1]:   message: 'connect ECONNREFUSED 172.99.86.10:51078' }
2016-03-25T03:10:11.089522+00:00 app[web.1]: { [MongoError: connect ECONNREFUSED

**Comment by hasrants** [comment]
resolved -  was ACR security on ObjectRocket

**Comment by LBKevinSibue** [comment]
I made an app with Parse framework and parse my server hosted on AWS. And I too have the same problem: 'The data couldn't be read beacause it is not in the correct format. "

This error appear for every query.

The only solution I found was to set the version of the parse-server (and its dependencies) to 2.2.10.

Do you have any idea ? I check my ACR security and all look fine.
