### ISSUE TITLE
FILE_KEY not passed as an argument to parse server

### ISSUE THREAD

**Issue by hellonoam** [ParsePlatform/parse-server-example#136]
I believe file key needs to be added here https://github.com/ParsePlatform/parse-server-example/blob/master/index.js#L14

**Comment by drew-gross** [comment]
File key isn't necessary unless you are migrating an app from Parse.com that contains files. The optional parts of configuration are documented in Parse Server repo.

**Comment by hellonoam** [comment]
I realize it's not necessary but would make it easier to migrate apps with files as well. And the change I'm proposing is really easy. No worries if this is too much work, I'll just fork this repo
