### ISSUE TITLE
AWS Deploy of commit 07c8649 and later fails (Parse Server 2.2.2)

### ISSUE THREAD

**Issue by Apptation** [ParsePlatform/parse-server-example#146]
Deploy of Parse Server 2.2.2 (commit 07c8649 and later) to AWS EB fails.

Command line of "eb deploy" shows:
ERROR: Failed to run npm install. Snapshot logs for more details.   
ERROR: [Instance: i-b04d752a] Command failed on instance. Return code: 1 Output: (TRUNCATED)..."/opt/elasticbeanstalk/containerfiles/ebnode.py", line 166, in npm_install
    raise e
subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v4.3.0-linux-x64/bin/npm', '--production', 'install']' returned non-zero exit status 1. 
Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/50npm.sh failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.
INFO: Command execution completed on all instances. Summary: [Successful: 0, Failed: 1].
ERROR: Unsuccessful command execution on instance id(s) 'i-b04d752a'. Aborting the operation.
ERROR: Failed to deploy application

EB Logs show, this specific error:
fatal error: gssapi/gssapi.h: No such file or directory

Full log file attached.
[TailLogs-1459447230978.out.txt](https://github.com/ParsePlatform/parse-server-example/files/198310/TailLogs-1459447230978.out.txt)

missing required libkrb5-dev or kerberos?

**Comment by drew-gross** [comment]
Unfortunately we can't support AWS specific issues here. If you do find a solution, though, please post it so that others can benefit it.

**Comment by ChrisGrant** [comment]
@apptation did you find the solution to this? I'm getting the same error.

**Comment by Apptation** [comment]
I no longer get this error with more recent versions of Parse Server
