### ISSUE TITLE
How can I get the user making the request?

### ISSUE THREAD

**Issue by gfpacheco** [ParsePlatform/parse-server-example#151]
Let's say I have the `ParseServer` mounted at `/parse`. Is there a way of getting the logged in user outside that route?

If a user makes a request to `/foo`, how can I get which user made the request?

```javascript
app.get('/foo', function(req, res) {
  // how to get the user here?
});
```

**Comment by drew-gross** [comment]
`req.user`.

**Comment by gfpacheco** [comment]
Are you sure about this? It's not working. As I said, `ParseServer` is mounted at `/parse`, my `/foo` route is just a simple express endpoint.

Is there any way of asking `ParseServer` which user is making a request based on the `req` received?

**Comment by drew-gross** [comment]
Ah, sorry, I missed that. If your request contains the users session token, you can use that to get the user. Check the headers of the request.

**Comment by gfpacheco** [comment]
I just cloned the repo, and made a few changes on the test page to test the authentication:

First I added Parse JS SDK to the page and added a button to authenticate and another to test:

```html
<script src="http://www.parsecdn.com/js/parse-latest.js"></script>
<a href="#" id="step-5-btn" class="step--action-btn">Authenticate</a>
<a href="#" id="step-6-btn" class="step--action-btn">Test</a>
```

Then I initialized Parse:

```javascript
Parse.initialize('myAppId');
Parse.serverURL = 'http://localhost:1337/api/v1';
```

Authenticate on button click:

```javascript
this.bindBtn('#step-5-btn', function(e) {
  Parse.User.logIn('username', 'password').then(function(data) {
    alert('ok');
  });
  e.preventDefault();
});
```

Make a request to test it:

```javascript
this.bindBtn('#step-6-btn', function(e) {
  XHR.GET('/foo');
  e.preventDefault();
});
```

And created the route on server:

```javascript
app.get('/foo', function(req, res) {
  console.log(req.user);
  console.log(req.headers);
  res.status(200).send('ok');
});
```

And there's where I can get the user. No user, no session, no header.

I already know that Parse saves the user data on localStorage and not cookies, so I can't just get them server side.

I wonder what's the "right" way of doing this kind of stuff.

**Comment by drew-gross** [comment]
Probably the right way to this will be to use a Cloud Code function, and use the Parse SDK to call the function.

**Comment by gfpacheco** [comment]
I get it, but this way my whole express server will be of no use, since I'll have to write all the code on Cloud Code "sub-server". Is that right?

**Comment by drew-gross** [comment]
Yes, part of the magic of Parse is that you don't have to think about headers and user sessions and so on, as the Parse SDK handles that for you. You can still do everything manually if you want using the REST API, and sometimes there are good reasons to do it that way, but it will be more work.

You might be able to try using express routes that override some Parse Server routes, like this:

```js
app.post('/your_parse_mount/functions/foo', function(req, res) {...})
```

And then use the Parse SDK or REST API to call the function, that way you will have access to all the info the Parse SDK sends across, but in an express route. None of us have tried that, though, so if you can make it work, let us know how you did it and if you ran into any issues.
