### ISSUE TITLE
Unauthorized error when accessing Parse API

### ISSUE THREAD

**Issue by vincentbello** [ParsePlatform/parse-server-example#16]
I am following the local development instructions but any calls to `http://localhost:1337/parse` return `{"error":"unauthorized"}`. I am correctly replacing `appId` and `masterKey` inside of `index.js` and yet I still get the error.
What more can I try? Are there logs I can sift through to see what the issue is?
Thanks.

**Comment by gfosco** [comment]
See my comment and continue this in: #19
