### ISSUE TITLE
Deploy parse server example to Digital Ocean

### ISSUE THREAD

**Issue by Faisal-nfl** [ParsePlatform/parse-server-example#160]
I successfully deployed parse server example to heroku and access it with parse dashboard.

Now I want to deploy it to Digital Ocean but I 'm not getting any clue that how to achieve this. I already spent hours on this but didn't find anything enough clear to follow.

Advise to towards right direction

**Comment by drew-gross** [comment]
Digital Ocean wrote a guide you can follow: https://www.digitalocean.com/community/tutorials/how-to-run-parse-server-on-ubuntu-14-04
