### ISSUE TITLE
Update Parse-Server-Example

### ISSUE THREAD

**Issue by kwstasna** [ParsePlatform/parse-server-example#162]
Hello.
I'm tottaly new to this and i want your help.
I've managed to install everything and even migrate my data to the Parse-Server v. 2.2.6 inside parse-server-example.
How can i update the parse-server inside the parse-server-example to 2.2.7??
I 'm running it at Ubuntu 14.04.
Any helpful command that i must run ?
Thanks a lot !

**Comment by pantri** [comment]
Are you running it in Express (i.e: Parse Server Example)?  If so, I believe that you can just replace the node.js installation, keeping your database & config files.  Best thing to do is to create a new install in 2.2.7, then copy over your database & config files (leaving your original install untouched incase you hit problems & need to revert back.

**Comment by kwstasna** [comment]
@pantri  you know now the parse-server-example in express uses the latest parse-server version?

**Comment by pantri** [comment]
@kwstasna I don't fully understand your question.  Are you asking whether parse-server-example contains the latest version of Parse Server?

**Comment by kwstasna** [comment]
@pantri  no worries i just did what you said and its the v2.2.7 thanks a lot!
