### ISSUE TITLE
Get this Error, but still can't see any parse data on heroku? 

### ISSUE THREAD

**Issue by nexslab** [ParsePlatform/parse-server-example#163]
Parse Server deploy Heroku
2016-04-16 18:24:51.824 ParseStarterProject-Swift[37025:10606060] [Error]: {"code":1,"message":"Internal server error."} (Code: 1, Version: 1.12.0)
Object has been saved.

Help thanks: what to do?

**Comment by pantri** [comment]
Start again & follow this: https://www.youtube.com/watch?v=Cp3VRKrnZ2o

Sounds like you're missing something somewhere.  You might want to also follow the same guys guide for installing the Parse Dashboard.

**Comment by dameon** [comment]
nexslab, did you every fix this issue? if so how?

**Comment by nexslab** [comment]
Hi Dameon, i figured out how to fix that problem.You'll need to to create another entry in your heroku settings : add a new key call DATABASE_URI --> and the value should be the same as your MONGODB_URI  save and compile your Xcode project it should work after this if not let me know.

**Comment by dameon** [comment]
Hi, nexslab, I REALLY appreciate your assistance. I'm up and running now. 
Thanks

**Comment by jarturohec** [comment]
@nexslab The MONGO_URI key worked for me to fix the problem. Thanks!

**Comment by Arjunkalidas** [comment]
@nexslab you are simply amazing. How did you figure this out? Saved my day man. Thanks a lot!
