### ISSUE TITLE
AWS deployment link in readme is not working

### ISSUE THREAD

**Issue by handymoby** [ParsePlatform/parse-server-example#170]
The link doesn't work for me, the dialog box in AWS doesn't seem to load the example, I manually loaded the zip file in the link, doesn't work either, any one has similar issue?

**Comment by drew-gross** [comment]
We've actually had a lot of issues with that button, most of which can only be fixed by Amazon. There is even an open PR to remove all the buttons. I'd recommend avoiding the use of those buttons and either deploying manually, or using a managed Parse service.
