### ISSUE TITLE
What can be the reason for this

### ISSUE THREAD

**Issue by saurabhkhare2004** [ParsePlatform/parse-server-example#172]
![image](https://cloud.githubusercontent.com/assets/18545638/14837202/e72e720a-0c33-11e6-922f-da3d5a27bb1f.png)

Why is the app showing unauthorized and for other cannot connect to server?

Is it so that the app name should be same in parse as well as heroku? and thats why it is showing unauthorized. What is the solution for this. What changes we need to make to index,js to change from mongodb addon to third party mlab database?

Regards

Saurabh Khare

**Comment by drew-gross** [comment]
The app name doesn't matter. One of your other settings must be wrong (url, master key, etc) or maybe your app server is actually not running.

**Comment by saurabhkhare2004** [comment]
Is it important to update index.js after automatic deployment through deploy heroku button? The URL, master keys are fine.What can be the reason for app server not running? Please brief.

**Comment by drew-gross** [comment]
Sorry, I can't help you with Heroku specific issues.

**Comment by saurabhkhare2004** [comment]
I want to know in relation to this: https://github.com/codepath/android_guides/wiki/Configuring-a-Parse-Server
 Is it important to update index,js after migrating to heroku through above? Please throw some light on this. Or index.js is automatically updated.

**Comment by drew-gross** [comment]
That guide was not written by us. Please contact the author of the guide for help.

**Comment by saurabhkhare2004** [comment]
Thanks for the help. OK, I am contacting Roger.
