### ISSUE TITLE
Proper use of useMasterKey() in Cloud Code?

### ISSUE THREAD

**Issue by ZacharyKhan** [ParsePlatform/parse-server-example#174]
Currently, I am using the Master Key in my Cloud Code using Parse.Cloud.useMasterKey(). To my understanding, this is no longer the way to do it with Parse-Server. 

Here is an example of how I am writing functions in my Parse Server Cloud Code

<img width="818" alt="screen shot 2016-04-27 at 5 47 51 pm" src="https://cloud.githubusercontent.com/assets/14354004/14872609/cb08478a-0ca2-11e6-9a3d-e3e03a7c2413.png">

To my understanding, all get(), find() and save() functions now must implement {useMasterKey:true}. Could someone clear this up for me?

**Comment by drew-gross** [comment]
Pass `useMasterKey: true` in the same options object that contains your `success` callback.

**Comment by ZacharyKhan** [comment]
can you please give me an example of how to use it, I don't quite understand how to use it in my code

**Comment by ZacharyKhan** [comment]
Hello?

**Comment by drew-gross** [comment]
`query.get(friendRequestId, { useMasterKey: true, success: ... });`

**Comment by ZacharyKhan** [comment]
Thank you!
