### ISSUE TITLE
After changing to my original cloud code npm start will not run 

### ISSUE THREAD

**Issue by sivi29y** [ParsePlatform/parse-server-example#182]
this is the error I get: 

npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "bugs" "parse-server-example"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! path xdg-open
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn xdg-open

npm ERR! enoent spawn xdg-open ENOENT
npm ERR! enoent spawn xdg-open ENOENT
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

How can I check this. Please tell me if more data is needed

**Comment by drew-gross** [comment]
The error message says there is a missing file somewhere. Check your cloud code file location.

**Comment by sivi29y** [comment]
should this : var userQuery = new Parse.Query("_User");
be replaced with new Parse.Query(Some other location) ? What should that be if so?

**Comment by sivi29y** [comment]
is Parse.Cloud.beforeDelete  supported ?

**Comment by sivi29y** [comment]
Hi Drew thanks, I think i spotted the problem  (Parse.Cloud.job is not a function). But please still if you can answer my other questions do because I have to make it work ..
