### ISSUE TITLE
{"error":"unauthorized"}

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-server-example#19]
Making a curl request to a Heroku Parse server returns {"error":"unauthorized"} .. I have everything setup and running along with the db connection to mongolab.

![image](https://cloud.githubusercontent.com/assets/519563/12708062/56f42f6c-c850-11e5-8d27-8cb4cfa570df.png)

any ideas?

**Comment by gfosco** [comment]
Did you happen to set a rest api key, client key, or javascript key?... If you set any of these keys in ParseServer intialization, then all requests must have a key.

**Comment by zebapy** [comment]
I'm also getting unauthorized when I hit my API endpoint that parse is set up on. No rest api, client, or js keys set in my parse config.

**Comment by gateway** [comment]
Please do not close issues w/o the original owner replying .. To answer your question I do have these keys set up that's why I'm posting the issue

**Comment by gateway** [comment]
Ok, I was able to get this to work now.. , Might be worth updating the actual curl call in the docs to state if you have x,y,z keys you need to add those.. anyone just doing this will probably fail.. .. thanks

**Comment by gfosco** [comment]
We definitely need to keep updating the docs and making things clearer.  Thanks.
