### ISSUE TITLE
Multiple exercise：could code

### ISSUE THREAD

**Issue by scoield** [ParsePlatform/parse-server-example#193]
here is my cloud code 
`Parse.Cloud.define("follow", function(request, response) {
  var targetId=request.params.objectId;
  var user=request.user;
  console.log("follow--------->"+targetId);
  response.success(JSON.parse("{}"));
  var follow = new Parse.Object("Follow");
  follow.set("from", request.user);
  follow.set("to", request.user);
  follow.set("date", Date());
  // follow.save();
console.log("save--------->"+targetId);
});
`
and console log:
follow--------->cNvZ2JgiXe
save--------->cNvZ2JgiXe
follow--------->cNvZ2JgiXe
save--------->cNvZ2JgiXe
follow--------->cNvZ2JgiXe
save--------->cNvZ2JgiXe
follow--------->cNvZ2JgiXe
save--------->cNvZ2JgiXe

why 4 times?

**Comment by drew-gross** [comment]
If you are only calling the cloud function once, it should only execute once. We have tests that ensure that is the case, though. If you are able to consistently reproduce this issue, can you post a complete code that does so? Including server initialization and the SDK calls you make?

**Comment by scoield** [comment]
i know the solution,when i call the cloud function in Application Oncreate(),it would cause Multiple exercise,but i call it in my MainActivty onCreate(),then only one;thanks anyway
