### ISSUE TITLE
Unable to connect to Parse API

### ISSUE THREAD

**Issue by david-koch-pro** [ParsePlatform/parse-server-example#199]
Here is my server configuration. (index.js)
![screen-shot-2016-05-24-at-10 54 37](https://cloud.githubusercontent.com/assets/16528614/15498171/be425f5c-219e-11e6-866c-e730101173b7.jpg)

And here is my cloud code. (/cloud/main.js)
![screen-shot-2016-05-24-at-11 01 44](https://cloud.githubusercontent.com/assets/16528614/15498247/19a5bbb4-219f-11e6-91c1-9827974debfa.png)

For testing, I run this command.

![screen-shot-2016-05-24-at-11 05 31](https://cloud.githubusercontent.com/assets/16528614/15498430/eac12cd8-219f-11e6-9868-39d5a946b4b1.jpg)

Then I got this message.
{"code":141,"error":"XMLHttpRequest failed: \"Unable to connect to the Parse API\""}

I tried all reference of Git about this problem but couldn't fix this problem. Please help me.......

**Comment by Kasparas42180** [comment]
Have you configured your process.env.SERVER_URL variable?

**Comment by david-koch-pro** [comment]
Excuse me, I don't know how to set process.env.SERVER_URL. I thought it will be set automatically.

**Comment by david-koch-pro** [comment]
And I could get server log and it was running well.

**Comment by Kasparas42180** [comment]
Have you looked at .ebextensions/app.config file? Myself I run parse-server on Heroku, I set my environmental variables by using external module - https://www.npmjs.com/package/dotenv

**Comment by david-koch-pro** [comment]
![screen-shot-2016-05-24-at-11 24 35](https://cloud.githubusercontent.com/assets/16528614/15499084/9929092e-21a2-11e6-9eaf-056065c05aa3.jpg)

**Comment by david-koch-pro** [comment]
I already set environmental variables.

**Comment by Kasparas42180** [comment]
If it still doesn't work, I don't know how to help. Perhaps somebody with Elastic Beanstalk expertise will.

**Comment by david-koch-pro** [comment]
Please teach me how to use "dotenv". It might be able to help me.

**Comment by Kasparas42180** [comment]
Please read the instructions on the page I've sent you. I cannot explain any better than that.

**Comment by david-koch-pro** [comment]
Thank you Kasparas42180

**Comment by stalehard** [comment]
I have same problem. I use amazon EB as hosting. To fix problem i restart application, but problem again repeated. 

Logs:
`ParseError {
  code: 100,
  message: 'XMLHttpRequest failed: "Unable to connect to the Parse API"' }`

**Comment by jeffhuangtw** [comment]
You may check the document here:
http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ebextensions-optionsettings.html

Example .ebextensions/options.config
option_settings:
  - option_name: SERVER_URL
    value: '_YOUR_SERVER_URL_'
