### ISSUE TITLE
Mailgun adapter with parse-server-example

### ISSUE THREAD

**Issue by zualas** [ParsePlatform/parse-server-example#209]
Is there a clear instruction somewhere on how to setup Mailgun with parse-server-example? My application runs on Heroku, and I have been looking for more than a week without success. [Asking at Stackoverflow](http://stackoverflow.com/questions/37277161/setup-mailgun-for-parse-server-example-on-heroku) didn't help either.

**Comment by drew-gross** [comment]
Check the README for Parse Server .

**Comment by zualas** [comment]
Sorry if there is something very obvious that I don't understand, but I don't use the Parse Server directly. I have parse-server-example on Heroku, and as such I do not have a repository for Parse Server where I could enter mailgun-specific setup. Is there a way to setup only parse-server-example in order to be able to use Mailgun?

**Comment by patkozlowski** [comment]
You need to install the parse server simple mailgun adapter using npm.  Just go to the root of your parse-server-example directory:  npm install parse-server-simple-mailgun-adapter
