### ISSUE TITLE
Masking / Removing field data of a class

### ISSUE THREAD

**Issue by mchun** [ParsePlatform/parse-server-example#215]
I know that there is class-level permission that disallow people to read certain class.
But can I protect certain field of a class (like the email of users) by removing/hashing that in parse-server before passing the result to clients?

It was raised by someone previously when the server is hosted by parse.com, but now when we can host the server ourselves, I wonder if it will be possible. Thanks.
https://www.parse.com/questions/protecting-user-email

**Comment by drew-gross** [comment]
Currently the only way to do that is through a cloud code function. I've been toying with the idea of "private fields" though that would let you do that though.

**Comment by mchun** [comment]
Thanks! Good to hear that. I guess many people will find that useful too!

**Comment by mchun** [comment]
I made a mistake of open it as an issue of parse-server-example instead of parse-server. Anyway, issue closed.
