### ISSUE TITLE
parse-server-example on Digital Ocean with PM2

### ISSUE THREAD

**Issue by Sadmansamee** [ParsePlatform/parse-server-example#249]
I was trying to install **parse-server-example** by cloning on **Digital Ocean** with P**M2**, https://www.digitalocean.com/community/tutorials/how-to-migrate-a-parse-app-to-parse-server-on-ubuntu-14-04 with this I have to install **parse-server**, Can I install  **parse-server-example** from **git** anyway? or what will be the proper way for deploying **parser-server-example** with **pm2**

**Comment by majidhassan** [comment]
You could run the index.js provided in parse-server-example using pm2. Or you could npm install parse-server and run it separately.

Personally, I prefer running it without parse-server-example. You could check my [repo](https://github.com/appductionstudios/digitalocean_parse), maybe it could be helpful in your case.

**Comment by Sadmansamee** [comment]
Thanks for replying, checking
