### ISSUE TITLE
Schema mismatch for _Session.expiresAt; expected date but got string

### ISSUE THREAD

**Issue by CaseyTeeps** [ParsePlatform/parse-server-example#28]
After migration, attempting to log a user in results in a status=400. Used the provided parse-server-example code.

[Error]: schema mismatch for _Session.expiresAt; expected date but got string (Code: 111, Version: 1.12.0)

**Comment by CaseyTeeps** [comment]
Manual Fix is changing _SCHEMA session.date to a string.

**Comment by gfosco** [comment]
This should also be fixed in 2.0.4 of parse-server.  Thanks.
