### ISSUE TITLE
Received an error with invalid JSON

### ISSUE THREAD

**Issue by chibchombiano26** [ParsePlatform/parse-server-example#3]
i received 107

![parse](https://cloud.githubusercontent.com/assets/2654397/12664791/98e5d788-c600-11e5-93d3-163523b47bd9.PNG)

when i made any call

Parse.initialize("hefesoft", "h123456");
Parse.serverURL = 'http://parse-server-chibchombiano26.c9users.io/parse'

code: 107
Received an error with invalid JSON

![parse2](https://cloud.githubusercontent.com/assets/2654397/12664825/d95ff5e6-c600-11e5-9dec-b92346c70e30.PNG)

https://ide.c9.io/chibchombiano26/parse-server

Thanks in advance!

**Comment by gateway** [comment]
sorry to take over the post but how did you get this working, where did you get the api keys, and set the db .. ? any chance for a better howto then listed on the readme..

**Comment by jamesyu** [comment]
@gateway take a look at the full guide here: https://parse.com/docs/server/guide

**Comment by benjaminhallock** [comment]
Ya I'm stumbling through this, currently getting "error: unauthorized".

**Comment by Harsha93** [comment]
Same here error:unauthorized :/

**Comment by benjaminhallock** [comment]
Okay, I was able to create an Object locally @Harsha93, make sure your request has the correct app id of "myAppId".

**Comment by benjaminhallock** [comment]
But App Transport Security is stopping my requests I believe.

**Comment by gfosco** [comment]
You'll need to put it behind HTTPS in most public use-cases.

**Comment by chibchombiano26** [comment]
thanks @gfosco  really in my case  i discovered the error was presented when i use an oudated version of parse javascript client

![image](https://cloud.githubusercontent.com/assets/2654397/12674552/cb5d18c4-c651-11e5-87f8-9476f2b218bc.png)

**Comment by gateway** [comment]
I ran into this as well, but silly me forgot to add /parse to my url.. maybe a doc update to help anyone with this?
