### ISSUE TITLE
Push Notification Issue

### ISSUE THREAD

**Issue by michaelsalvador** [ParsePlatform/parse-server-example#308]
Hello,

Over the past day or so I've been trying to configure push notifications and have been running into an issue. I'm able to call the push notification in the cloud code from the client side, but the push never actually gets sent to a device. When I go on Parse-Dashboard and check the past pushes, it shows the notification, has a green "Sent" on the side, but then the number that represents how many were sent says 0. Also, when I look at more details, it says that 0 were delivered. 

Does anyone have any idea what could be causing this? Thanks in advance.

**Comment by brianyyz** [comment]
How is your app deployed? Is it via TestFlight or is it in Production. You will have a different set of certificates for the environments.

**Comment by michaelsalvador** [comment]
Currently I'm using the development certificate. I'm using this format within the index.js:

ios: {
        pfx: '/file/path/to/XXX.p12',
        bundleId: '',
        production: false
      }

I've already double checked that all of these things are correct.

**Comment by brianyyz** [comment]
I'll dig back through my notes - I had a similar problem when I moved my app to production and it was something very obscure as I recall.

**Comment by brianyyz** [comment]
I went back and all I could find was a cryptic note that I had to revoke my certs and create new ones to resolve this problem. Have you tried that ?

**Comment by michaelsalvador** [comment]
I revoked my developer certificate, got another one, still not working. Which adapter do you use to send the notifications?

**Comment by michaelsalvador** [comment]
Okay- this might give some indication. I'm trying to use the parse-server-push-adapter, and when this stuff:

push: {
    ios: [
      {
        pfx: '', // Dev PFX or P12
        bundleId: '',
        production: false // Dev
      },
      {
        pfx: '', // Prod PFX or P12
        bundleId: '',  
        production: true // Prod
      }
    ]
  },

is typed in correctly (all keys are what they're supposed to be), the app no longer connects to Heroku. However, when they are set up incorrectly, the app connects perfectly.

**Comment by michaelsalvador** [comment]
Got it working!

**Comment by brianyyz** [comment]
Cool - you beat me to it - my only other suggestion was to adjust your certificate path to a relative one rather than absolute at /

Glad it is working now.
