### ISSUE TITLE
REST API is creating objects with undefined values

### ISSUE THREAD

**Issue by arckdash** [ParsePlatform/parse-server-example#309]
Hi everybody! I'm having a really big issue, it has been four days now without finding a solution for this!

my problem is that I'm trying from my php server make a POST to my instance of parse-server-example, and the records is being created but with undefined values.

The same post from Postman works perfectly fine.

The post from my server to (http://api.parse.com/1) work fine as well.

In postman and on my php server I'm using the same headers (X-Parse-Application-Id => 'XXXXXXXXXX').

In my parse-server-example instance I've defined the applicationId and masterKey, but for the request I'm just usig application as header.

So I can't understand why the POST works well on Postman and not from the php server?

Any idea?
Thanks.

**Comment by brianyyz** [comment]
Can you post your parse server's start up ? (with keys blanked out) Are you specifying necessary key values other than just app_id ?

**Comment by arckdash** [comment]
Hi, thanks for replying, yes here is my current configuration:

var api = new ParseServer({
  databaseURI: 'mongodb://XXXXXXXXXXXXXXXXXXXX',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'XXXXXXXXXXXXXXXXXXXXXX',
  masterKey: process.env.MASTER_KEY || 'XXXXXXXXXXX', 
  serverURL: process.env.SERVER_URL || 'http://myServerUrl/parse',
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  }
});

**Comment by brianyyz** [comment]
I use the SDK so not certain on this but since you are using HTTP POST wouldn't you have to specify the X-Parse-REST-API-Key in your start up and headers ?

**Comment by arckdash** [comment]
Well I thought that, and of course I did the test of set the Rest API Key on my server and on my headers as well, but the result is still the same.

Also I read the documentation twice, and it says that with the applicationId is good enough to secure the application and if you don't define any other extra key, it should work fine (and It does from postman! :S)

**Comment by arckdash** [comment]
Get and PUT are working fine, but with POST I'm having the same issue! :S

Any ideas ?
Thanks

**Comment by arckdash** [comment]
Saddly for me I need to provide a solution as soon as possible, so my solution for this was just make 
a POST for creating the object that I need to and then use the objectId returned from the POST, to make an upload (using PUT) with the same data, and it's working fine now.

the error is strange and I couldn't find a solution yet, but I'm still open to suggestions if any. 

Cheers.
