### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by guilhermecvm** [ParsePlatform/parse-server-example#35]
If you are having problem with npm. Try installing does packages first:
apt-get install g++ libkrb5-dev

**Comment by nerakhon** [comment]
Which doesn't solve the problem, given the node image used as template for building the parse docker (node:latest) based on jessie and apt repos of this don't contain the package.

I have in the end solved it by switching the base image from node:latest to nodesource/trusty:4.3.1. But the docker file is anyway wrong and non-functional.

The npm install fails 95% of times. Sometimes when you keep trying long enough the build will actually succeed but that's really not a desired outcome I hope :).

**Comment by gfosco** [comment]
Not clear to me what the actual issue is, or if it's still occurring.  Going to close this, if you're still having trouble please re-open a new issue with more details.  Thanks.
