### ISSUE TITLE
problem when using Mongolabs replicaset

### ISSUE THREAD

**Issue by adamontherun** [ParsePlatform/parse-server-example#36]
When I setup my server with the 'Deploy to Heroku' button and use the standard free MongoLabs DB, I'm able to connect with my iOS app no problems.

When I upgraded by MongoLabsDB by following these [instructions](https://devcenter.heroku.com/articles/mongolab#changing-plans) I'm no longer able to connect from my App. I'm getting the following error:

 [Error]: {"code":1,"message":"Internal server error."} (Code: 1, Version: 1.12.0)
2016-02-03 10:37:36.494 Remark[6651:4008311] [Error]: Failed to run command eventually with error: Error Domain=Parse Code=1 "{"code":1,"message":"Internal server error."}" UserInfo={error={"code":1,"message":"Internal server error."}, NSLocalizedDescription={"code":1,"message":"Internal server error."}, code=1}

**Comment by mattcreager** [comment]
Hey @adamontherun, We've got some friends over at MongoLabs, we're going to see if they can drop in and lend a hand :)

**Comment by chrisckchang** [comment]
Looks like there's an open ticket for this with both Heroku and MongoLab involved, so we'll continue communications there.

**Comment by adamontherun** [comment]
@mattcreager @chrisckchang thanks guys, i appreciate you jumping on this. Makes the Parse shutdown easier to deal with!

**Comment by benc555** [comment]
@chrisckchang any update?
