### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by jimok82** [ParsePlatform/parse-server-example#4]
when trying to install the example, I get the following error:

`
> parse-server-example@1.0.0 start /usr/share/parse/server
> node index.js

/usr/share/parse/server/node_modules/parse-server/index.js:145
    request(options, (error, response, body) => {
                                              ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/share/parse/server/index.js:5:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! Linux 4.1.0-x86_64-linode59
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.41
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! parse-server-example@1.0.0 start: `node index.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the parse-server-example@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-server-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-server-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parse-server-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/share/parse/server/npm-debug.log`

I have made no changes to the parse-server-example provided.

**Comment by gfosco** [comment]
What version of Node?  This requires >=4.1

**Comment by jimok82** [comment]
It looks like I was using v0.10.41 which is odd.. It worked fine once I switched to Node.JS 5.x
