### ISSUE TITLE
Getting Parse Server Updates on Parse Server Example

### ISSUE THREAD

**Issue by stevenmick** [ParsePlatform/parse-server-example#41]
This might be a remedial question, but I was having [this issue](https://github.com/ParsePlatform/parse-server/issues/94). I set up my Parse Server with Heroku & MongoLab using the _parse-server-example_ and even after the issue was fixed and closed, I still get the same error. 

So I'm wondering if there's a way for me to use this server example and have it depend on the updated Parse Serve code? Or do I have to wait for an official release with the fixed issue?

**Comment by drew-gross** [comment]
You can update the package.json file to use the latest version of parse-server. Once you do that, please submit a pull request so other people won't have the same issue!
