### ISSUE TITLE
Error modifying user function

### ISSUE THREAD

**Issue by CaseyTeeps** [ParsePlatform/parse-server-example#42]
Example Using:
`    [[PFUser currentUser] setObject:[NSNumber numberWithBool:NO] forKey:@"inOffice"];
    [[PFUser currentUser] saveInBackground];`

Log output:
`
[Error]: cannot modify user function () {
  return this.data.objectId || this.query.objectId;
} (Code: 206, Version: 1.12.0) `

Hosting the current parse-server-example on mongolab/heroku

**Comment by gfosco** [comment]
This has been fixed in a later version, please update.  Thanks.
