### ISSUE TITLE
 "could not find the source blob" error while using Heroku button

### ISSUE THREAD

**Issue by fatuhoku** [ParsePlatform/parse-server-example#45]
![screen shot 2016-02-06 at 11 56 47](https://cloud.githubusercontent.com/assets/430233/12866530/c65e9c6c-ccc8-11e5-8fbf-cc87b19990a1.png)

**Comment by drew-gross** [comment]
cc @mattcreager

**Comment by hramos** [comment]
@fatuhoku were you able to deploy the sample app on a second attempt? I haven't been able to reproduce this.

**Comment by fatuhoku** [comment]
I haven't really had to try again — I just ended up setting up Heroku manually. I'll just close this issue until it re-arises.
