### ISSUE TITLE
DATABASE_URI not specified using MongoLab

### ISSUE THREAD

**Issue by bachma0507** [ParsePlatform/parse-server-example#47]
I get the following when running npm start, which indicates 'DATABSE_URI not specified':
> $ npm start

> parse-server-example@1.0.0 start /Users/barry/parseexample
> node index.js

>DATABASE_URI not specified, falling back to localhost.
>parse-server-example running on port 1337.

I am not running MongoDB locally but using MongoLab and this is what I have in my index.js:
>var express = require('express');
>var ParseServer = require('parse-server').ParseServer;

>var databaseUri = process.env.DATABASE_URI || process.env.MONGOLAB_URI

>if (!databaseUri) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
}

>var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://myuserdb:mydbpassword@ds055555.mongolab.com:55555/myparsedb',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppID',
  masterKey: process.env.MASTER_KEY || 'myMasterKey' //Add your master key here. Keep it secret!
});
// Client-keys like the javascript key or the .NET key are not necessary with parse-server
// If you wish you require them, you can set them as options in the initialization above:
// javascriptKey, restAPIKey, dotNetKey, clientKey

>var app = express();

>// Serve the Parse API on the /parse URL prefix
>var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);

>// Parse Server plays nicely with the rest of your web routes
>app.get('/', function(req, res) {
  res.status(200).send('I dream of being a web site.');
});

>var port = process.env.PORT || 1337;
app.listen(port, function() {
    console.log('parse-server-example running on port ' + port + '.');
});

I can't figure out why I am getting 'DATABASE_URI not specified', when I do have it specified. Unless it's because I'm using MongoLab and using the incorrect syntax.

**Comment by jameswilsterman** [comment]
How did you end up solving this?

**Comment by bachma0507** [comment]
It was referencing the wrong index file.

**Comment by mateo951** [comment]
Having the exact same issue over here.. How did fix your inde.js reference?

**Comment by bachma0507** [comment]
To be honest, I cannot recall this. I probably had another index.js file somewhere in there and deleted it. I think soon after trying parse server and mongo, I switched to backendless. It was the closes BaaS to Parse and works fine for me.
