### ISSUE TITLE
The data couldn’t be read because it isn’t in the correct format.

### ISSUE THREAD

**Issue by benjaminhallock** [ParsePlatform/parse-server-example#5]
Got my local and Heroku server up, but not clear if I'm supposed to generate classes manually or automatically. Keep getting caught on queries with the error  "The data couldn’t be read because it isn’t in the correct format."

Edit: Set this up as follows, I assume its supposed to work with minimal changes? What changes exactly is unclear. Does Heroku work out of the box, or do I have to pay?

`AppDelegate.m`
```
    [Parse initializeWithConfiguration:[ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration> configuration) {
        configuration.applicationId = @"myAppId";
        configuration.clientKey = What do I put here if I dont have a client key?;
//        configuration.server = @"http://localhost:1337/parse";
        configuration.server = @"https://MY-HEROKU-APP.herokuapp.com/parse";
    }]];
```

**Comment by gfosco** [comment]
Please provide the code and point out where the error is occurring.

**Comment by benjaminhallock** [comment]
I put this in 2 separate apps. All I was doing is a query on Class "_User" and a class "Chat". It failed with that error.

**Comment by benjaminhallock** [comment]
My cloud code was also causing an issue with heroku, tried to install twilio but it stopped working.

**Comment by benjaminhallock** [comment]
THAT FIXED IT NVM.

**Comment by benjaminhallock** [comment]
Also, I would avoid any PFUser anonymous code because that doesn't seem to work well with this setup. Just create a new user object.

**Comment by sekouperry** [comment]
I'm having the same problem. I'm having the server https://stormy-coast-58270.herokuapp.com. In Xcode I have it set to go to https://stormy-coast-58270.herokuapp.com/parse. When I run the code in simulator, an alert pops up saying unauthorized.
Any clue as to what I'm doing wrong?
I'm attaching the index.js that I have minus the keys/mongodb and the swift file.
Any help is appreciated.
Also if the kind folks at parse can have some sort of tutorial on setting this up on digital ocean, it would be great.
[Archive.zip](https://github.com/ParsePlatform/parse-server-example/files/110998/Archive.zip)

**Comment by gfosco** [comment]
You're sure you're using the same appId for both server and client?... I'd try the more permissive level of not setting any client keys on the server, only the app id and master key.

**Comment by gfosco** [comment]
Is the user logged in and providing a (invalid?) session token to the parse-server instance?...

**Comment by sekouperry** [comment]
Well on the simulator, I am logged into the app. Do you suggest I not be logged in and try again?
Should I clear the sessions out of moongodb?
Yes both server and client have the same appid. I've tried without clientid as well.

**Comment by sekouperry** [comment]
Or perhaps I should start with a blank parse app?
Thoughts?

**Comment by sekouperry** [comment]
Starting from a blank database works in my case. Right now I'm migrating the data I have on parse hosted to the database and see if that breaks anything.

**Comment by benjaminhallock** [comment]
Yes I wasn't migrating data, but good luck with that. I made a short tutorial for some friends [https://gist.github.com/benjaminhallock/5c26e9ef6b86abdafe45](url)

**Comment by gfosco** [comment]
Closing for now, but if you can pinpoint an issue, please open a bug on the parse-server repo.

**Comment by LBKevinSibue** [comment]
I made an app with Parse framework and parse my server hosted on AWS. And I too have the same problem: 'The data couldn't be read beacause it is not in the correct format. " 

The only solution I found was to set the version of the parse-server (and its dependencies) to 2.2.10.

Do you have any idea?

**Comment by commando24** [comment]
I was getting the same problem but i changed the server in ParseClientConfiguration to
https://YOUR-APP-NAME-HERE.herokuapp.com/parse
