### ISSUE TITLE
Request header field X-Parse-Application-ID is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by VesperDev** [ParsePlatform/parse-server-example#53]
Hello such community I have the following question'm trying to upload a file, but I have the following error

![captura](https://cloud.githubusercontent.com/assets/14016458/12971119/f02efd06-d05c-11e5-8385-422c3aa8038e.PNG)
[
![captura2](https://cloud.githubusercontent.com/assets/14016458/12971126/01dca6d4-d05d-11e5-83a4-24dffb75530b.PNG)
](url)

add these lines of code for testing file uploading #20 
change the application ID and the rest-api-key
and finally add a service to upload the file

     Upload: function(file) {

        var defer = $q.defer();
        var parseFile = new Parse.File(file.name, file);

        parseFile.save({
          success: function(savedFile) {
            defer.resolve(savedFile);
          },
          error: function(error) {
            defer.reject(error);
          }
        });

        return defer.promise;

but it continues to appear the same mistake :(

MLHttpRequest cannot load https://xxxxxxxx/parse/files/4188biun0z82kklf3euc_400x400.jpeg. Request header field X-Parse-Application-ID is not allowed by Access-Control-Allow-Headers in preflight response.
main.js:43 Unable to connect to the Parse API

Anyone know how I solve this?

Thank you very much for your time

**Comment by drew-gross** [comment]
Have you set the correct serverURL including parse mount point in your app? If so, then this sounds like a CORS issue that we should fix. In the meantime, the workaround would be to host your parse server and your website on the same domain (including subdomain). This is definitely not the ideal situation, though, so we will definitely seek to address this bug. You could also submit a PR :)

**Comment by VesperDev** [comment]
hello @drew-gross replace the app-id and the rest-api-key

app.all('*', function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'PUT, GET, POST, DELETE, OPTIONS');
    res.header('Access-Control-Allow-Headers', 'accept, content-type,aa, bb, x-parse-session-token');
     // intercept OPTIONS method
    if ('OPTIONS' == req.method) {
      res.send(200);
    }
    else {
      next();
    }
});

aa = x-parse-application-id
bb = x-parse-rest-api-key

I make a small application to test that everything is working . the parse.initializate is this

Parse.initialize('cc','dd');
Parse.serverURL = 'https://urlheroku.com/parse';

cc = application_id
dd = javacript_key

all right even create a new document in mongodb no problem.
this detail when uploading a file.

I will be doing wrong?
thanks for you time.

**Comment by drew-gross** [comment]
We'll do some additional investigation. In the meantime, if you could provide a complete reproduction script or test case that would be very helpful (ie. a parse-server application and JS application that we can run and instantly see the problem)

**Comment by asContagious** [comment]
I'm having this issue just trying to connect through the JS SDK: 
ERR Connection refused: 
 {code: 100, message: "XMLHttpRequest failed: "Unable to connect to the Parse API""}

**Comment by vbabaria** [comment]
+1 

https://github.com/ParsePlatform/parse-server/issues/408

**Comment by vxb8874** [comment]
ran into same bug and can't find any solution - would really appreciate any pointers

**Comment by drew-gross** [comment]
This issue is fixed in #390. If you don't want to wait for the next release, you can clone the repo and run the master branch.
