### ISSUE TITLE
Parse Query returns 141 unauthorized error

### ISSUE THREAD

**Issue by refre5h** [ParsePlatform/parse-server-example#54]
Followed the example and finished setting up Heroku and MongoDB. These 3 all worked:
```
curl -X POST \
  -H "X-Parse-Application-Id: myAppId" \
  -H "Content-Type: application/json" \
  -d '{"score":1337,"playerName":"Sean Plott","cheatMode":false}' \
  http://localhost:5000/parse/classes/GameScore
```
```
curl -X GET \
  -H "X-Parse-Application-Id: myAppId" \
  -H "X-Parse-Master-Key: myMasterKey" \
  http://localhost:5000/parse/classes/GameScore
```
```
curl -X POST \
  -H "X-Parse-Application-Id: myAppId" \
  -H "Content-Type: application/json" \
  http://localhost:5000/parse/functions/hello
```

I then wrote a simple query to get the GameScore class data:
```
Parse.Cloud.define('getGameScore', function(req, res) {
	var query = new Parse.Query("GameScore");
	query.find().then(function(results){
		res.success(results);
	},function(error){
		res.error(error);
	})
})
```

... and tried to call the function with this:
```
curl -X POST \
  -H "X-Parse-Application-Id: myAppId" \
  -H "Content-Type: application/json" \
  http://localhost:5000/parse/functions/getGameScore
```

... got this error:
`{"code":141,"error":{"message":"unauthorized"}}`

<img width="485" alt="screen shot 2016-02-11 at 5 10 46 pm" src="https://cloud.githubusercontent.com/assets/7074770/12996188/7972ded6-d0e2-11e5-9362-daf44fe812c8.png">

Am I missing anything, or is this a bug?

**Comment by estylehq** [comment]
No. you missed your application id and master key parse.com below on your code.

**Comment by drew-gross** [comment]
Do you have any client keys set in your server configuration? If you do, you will need to provide one of them in your request. You can also remove the client keys from your server configuration, as they are unnecessary in parse-server.

**Comment by refre5h** [comment]
@estylehq I did include the app id in the examples I provided. I also just tried including the master key, but it still gave the same error.
<img width="426" alt="screen shot 2016-02-11 at 11 36 41 pm" src="https://cloud.githubusercontent.com/assets/7074770/13001216/58cb91d8-d118-11e5-80df-66f5de1718a3.png">

@drew-gross I don't have any client keys set in the server config. Below you can see my config and constructor.
<img width="495" alt="screen shot 2016-02-11 at 11 26 52 pm" src="https://cloud.githubusercontent.com/assets/7074770/13001108/736645f2-d117-11e5-9063-77e03929239b.png">
<img width="385" alt="screen shot 2016-02-11 at 11 29 34 pm" src="https://cloud.githubusercontent.com/assets/7074770/13001109/7615b09e-d117-11e5-8bdc-0535fa0d003b.png">

Another reason why I suspect this could be a bug is that the "hello" function works, but not the "getGameScore".
```
// CALLING THIS ONE WORKED
Parse.Cloud.define('hello', function(req, res) {
  res.success('Hello from the other side!');
});
// CALLING THIS GAVE THE ERROR
Parse.Cloud.define('getGameScore', function(req, res) {
	var query = new Parse.Query("GameScore");
	query.find().then(function(results){
		res.success(results);
	},function(error){
		res.error(error);
	})
})
```

**Comment by refre5h** [comment]
I have found the solution here: [ParsePlatform/parse-server/issues/356](https://github.com/ParsePlatform/parse-server/issues/356)
Turns out I need to add the `serverURL` option.

**Comment by simonbengtsson** [comment]
I think the `serverURL` should either be included in the example or stressed more in the documentation.

**Comment by loftyet** [comment]
strongly agreed @simonbengtsson . it takes me another 15 mins to figure this out.
