### ISSUE TITLE
"eb create" for deployment to AWS fails due to NodeCommand parameter

### ISSUE THREAD

**Issue by Apptation** [ParsePlatform/parse-server-example#60]
ERROR: "option_settings" in one of the configuration files failed validation. More details to follow.
ERROR: Unknown or duplicate parameter: NodeCommand 
ERROR: Failed to launch environment.
                                
ERROR: Failed to launch environment.

**Comment by drew-gross** [comment]
This sounds like an issue with AWS. I'd encourage you to reach out to Abhishek (abhisin@amazon.com) who created the "Deploy to AWS" button for AWS specific help.

**Comment by abhiksingh** [comment]
For those running into the issue with the NodeCommand option setting when using the Docker platform on Elastic Beanstalk, you can simply remove the following lines from the app.config file in the .ebextensions folder:
`aws:elasticbeanstalk:container:nodejs:
    NodeCommand: "npm start"`

**Comment by neo01124** [comment]
thanks @abhiksingh that fixed it

**Comment by Apptation** [comment]
Thanks. There was also an ongoing thread in Parse-Server that mentioned
stepping up the minimum hardware on the AWS instance resolves the issue.
