### ISSUE TITLE
Unable to migrate from Parse dashboard to localhost mongodb server

### ISSUE THREAD

**Issue by abhilash2in** [ParsePlatform/parse-server-example#61]
I've changed index.js of the parse-server-example (cloned from git) to add my details

```
var api = new ParseServer({
  databaseURI: 'mongodb://localhost:27017', //also tried 'mongodb://localhost:27017/db'
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: 'my_app_id',
  masterKey: 'my_master_key'
});
```
I started my parse-server by doing `npm install` and then `npm start`
It says `parse-server-example running on port 1337.`

I started mongodb by doing `mongod --setParameter failIndexKeyTooLong=false`
And it says `waiting for connections on port 27017`
So, my mongodb server is running on `localhost:27017` and parse on `localhost:1337`

I've got a public url to mongodb through ngrok by doing `ngrok http 27017` (is this the right way?)
The url ngrok gave me was `http://1b610f2a.ngrok.io/ `
Opening `http://1b610f2a.ngrok.io/db` (db is the database where I want to migrate my existing parse app's database to) through a browser gives me `It looks like you are trying to access MongoDB over HTTP on the native driver port.`

From Parse dashboard settings, I'm trying to migrate to the mongodb server on localhost:27017. I tried database connection string as 'mongodb://localhost:27017' , `mongodb://1b610f2a.ngrok.io/db` , `mongodb://1b610f2a.ngrok.io` but for all of them, Parse migration tool says `No reachable servers`

What am I doing wrong? How do I migrate the parse app to localhost? It's a new app, so there is nothing on Parse which needs to be migrated to localhost. So, is there any other option to start using my app directly on localhost?

Also:

I got a public url to my local parse server by ngrok `ngrok http 1337`
On the android app's application class, I have:

```
Parse.initialize(new Parse.Configuration.Builder(getApplicationContext())
      .applicationId("I've entered application key here")
      .clientKey("I've entered client key here")
      .server("http://6d8e30f2.ngrok.io/parse")  //is the public address ngrok gave me
      .build());
```
 
Going to `http://6d8e30f2.ngrok.io/parse` from a browser gives me `{"error":"unauthorized"}`
So my parse server is running fine. 

But on running the app, the parse-server-example's response is `404 Not Found` `Cannot POST /classes/TestObject` and my mongodb server always says 'waiting for connections on port 27017'. Nothing connects to it when I run the parse server though I've mentioned the correct `databaseURI` in index.js of my parse-server, I always get 404 Not Found from parser-server-example

What am I doing wrong? Please help

**Comment by drew-gross** [comment]
Parse.com is unable to access your mongo installation. Please verify that you can connect to your mongo installation using the mongodb CLI using the same URI your are entering into the migration tool.

**Comment by abhilash2in** [comment]
What should the URI be when I'm migrating to mongodb on localhost?

**Comment by drew-gross** [comment]
Use the one generated by `ngrok`. You have to make sure you use the correct port as well.

**Comment by abhilash2in** [comment]
mongodb is running on port 27017. So i did 'ngrok http 27017' which gave me a http url but Parse.com doesnt take http urls for database migration. I replaced http:// with mongodb:// in the url given by ngrok, but Parse.com says No reachable servers

**Comment by drew-gross** [comment]
The `ngrok` website has instructions for using non-http services through `ngrok`. Since the mongo protocol isn't http, you will need to follow those instructions.
