### ISSUE TITLE
Error: Use of unresolved identifier 'ParseClientConfiguration'

### ISSUE THREAD

**Issue by alexyesiam** [ParsePlatform/parse-server-example#63]
Migrating from Parse to Heroku. 
I've updated my AppDelegate.swift file to include:

    let config = ParseClientConfiguration(block: {  
    (ParseMutableClientConfiguration) -> Void in

    ParseMutableClientConfiguration.applicationId = "...";  
    ParseMutableClientConfiguration.clientKey = "...";  
    ParseMutableClientConfiguration.server = "...";  
___________________________________________
My Podfile:

pod 'Parse', '1.11.0'
pod 'ParseUI'
pod 'Bolts'
pod 'ParseFacebookUtilsV4', '1.9.1'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'

One solution online says to update Parse to the current version (1.12.0).

However, I am using ParseFacebookUtils(1.9.1) in my app and Parse(1.12.0) does not work with ParseFacebookUtilsV4(1.9.1).
Ref: https://github.com/ParsePlatform/ParseFacebookUtils-iOS/issues/35

Is there a workaround for this?

**Comment by drew-gross** [comment]
According to that issue, a new version of the iOS SDK is due to be released soon. Hopefully that will solve your problem. If it doesn't you can reopen this issue or open an issue on the Obj-C SDK repo.
