### ISSUE TITLE
Resize Img

### ISSUE THREAD

**Issue by VesperDev** [ParsePlatform/parse-server-example#65]
Hello community can have the following questions and upload images to aws with S3Adapter now the question is how can I do to resize the images you will rise to aws

Thank you very much for your time.

**Comment by drew-gross** [comment]
I'd recommend browsing `npm` and looking for a module that does that. With open Parse Server you can use any `npm` module in your Cloud Code without modifications.

**Comment by VesperDev** [comment]
okay. Any link that can be done to make the resize?

**Comment by drew-gross** [comment]
At first glance this looks promising: `https://www.npmjs.com/package/resize` but I haven't tried it myself.
