### ISSUE TITLE
How to update parse-server deployed on AWS?

### ISSUE THREAD

**Issue by abhilash2in** [ParsePlatform/parse-server-example#67]
I can SSH into the AWS EC-2 instance where parse-server is located in `/var/app/current`

How can I update my parse-server running on the instance, using git?

**Comment by drew-gross** [comment]
You need to update your `package.json` file to include the version of `parse-server` that you want. You will then need to run `npm-install` in the folder where your server is located. This may be done automatically as part of your deploy process.

**Comment by abhilash2in** [comment]
These are the differences in the latest version, when compared to my version
"version": "1.0.0"
"parse-server": "~2.1"
"node": ">=4.3"

Should I updated all of these in my package.json?

Can you please elaborate on how to do this automatically on an AWS EC2
instance of the same?
Thanks

**Comment by abhilash2in** [comment]
These are the differences in the latest version, when compared to my version

```
"version": "1.0.0"
"parse-server": "~2.1"
"node": ">=4.3" 
```

Should I updated all of these in my package.json?

Can you please elaborate on how to do this automatically on an AWS EC2 instance of the same?
Thanks

**Comment by drew-gross** [comment]
you should only replace the `parse-server` and `node` entries
