### ISSUE TITLE
heroku folowed guide but error Cannot POST /parse

### ISSUE THREAD

**Issue by boardmain** [ParsePlatform/parse-server-example#72]
hi i followed the guide to deploy to heroku
but i have Cannot POST /parse if i try to do the post

**Comment by boardmain** [comment]
my mistake

**Comment by uttamraj143** [comment]
Hi even I am getting same error like Cannot GET /parse. could you please tell me what we have to do in order to run parse?

**Comment by hassansaeed999** [comment]
same error !! help plz
