### ISSUE TITLE
Application Error using Deploy with Heroku button

### ISSUE THREAD

**Issue by Alexintosh** [ParsePlatform/parse-server-example#74]
I used the Deploy with Heroku button but I'm getting an Application Error for every request I tried.

Any help?

**Comment by nickmeessen** [comment]
https://github.com/ParsePlatform/parse-server-example/blob/master/index.js needs to be updated to use **serverURL** as extra **required** parameter. (See https://github.com/ParsePlatform/parse-server/commit/81f5c682d4be392843de42d9c2b5b2a09a8367c8)

**Comment by johnbeynon** [comment]
I was just going to add this issue - we've (Heroku) have seen an uptick in this error today.

**Comment by johnbeynon** [comment]
Also, `app.json` needs to be updated to include it when the app is being deployed from Heroku buttons.

**Comment by rogerhu** [comment]
Added here: https://github.com/ParsePlatform/parse-server-example/pull/75

**Comment by bplus** [comment]
I'm still running into problems deploying with the button.  There are 2 new fields in the Config Variables section:
`PARSE_SERVER_URL` (this starts empty)
`SERVER_URL` (prepopulated with: http://myapp.herokuapp.com/parse )

Can anyone give examples of what those fields should be filled in with?

**Comment by rogerhu** [comment]
Trying to clean it up: https://github.com/ParsePlatform/parse-server-example/pull/77

**Comment by drew-gross** [comment]
You probably want to put `http://localhost/your_parse_mount` into `SERVER_URL`. @rogerhu removed the `PARSE_SERVER_URL` one, which was added accidentally.

**Comment by bplus** [comment]
I'm up and running with a `SERVER_URL` of:

https://[myappname].herokuapp.com/parse

Thanks for the help!

**Comment by rogerhu** [comment]
Apparently http://localhost doesn't work.  I'm going to submit a PR to point to https://[myappname].herokuapp.com/parse

**Comment by kbyatnal** [comment]
I'm having this exact same issue again....please help.

Logs:
2016-03-23T03:33:31.312222+00:00 app[web.1]: npm ERR!     npm owner ls parse-server-example
2016-03-23T03:33:31.312323+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-03-23T03:33:31.315828+00:00 app[web.1]: 
2016-03-23T03:33:32.057890+00:00 heroku[web.1]: Process exited with status 1
2016-03-23T03:33:34.400028+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=stylme.herokuapp.com request_id=f8e37e7c-0ae7-4e2f-a086-a370f6012039 fwd="152.3.43.136" dyno= connect= service= status=503 bytes=

**Comment by kukkadapukarhtik** [comment]
when i try to deploy with parse server example it successfully deployed but when i open the app it says application error .
![screen shot 2016-03-24 at 10 18 00 am](https://cloud.githubusercontent.com/assets/12559796/14008673/1a8df494-f1aa-11e5-82f4-36a7b5ae2224.png)

**Comment by rendragon83** [comment]
I am having this exact issue. I don't know what I could do differently.

**Comment by kevinjam** [comment]
Hey guys ..i m deploying parse on heroku but i m getting this error : 
Make sure to star the parse-server repo on GitHub!
I have tried but still failing ..how do u solve that ?

**Comment by jackintosh7** [comment]
I'm having the same issue, the server was working fine a week ago. I tried using it today and am now encountering that issue. I already have SERVER_URL.
