### ISSUE TITLE
Parse update ?

### ISSUE THREAD

**Issue by thamer898** [ParsePlatform/parse-server-example#79]
How to update my parse server to the latest version ?

**Comment by gfosco** [comment]
update package.json to use ~2.1.3 for the parse-server dependency and run `npm update`

That should get you the latest.

**Comment by thamer898** [comment]
Thank you but i download the parse server on Widows server 2012 how t apply the update command ?

**Comment by gfosco** [comment]
Should be the same... use npm from the command line.

**Comment by thamer898** [comment]
Thank you @gfosco

**Comment by thamer898** [comment]
but when i apply this method this message appear "you must provide server url" ?
