### ISSUE TITLE
Can't find module 'parse-server'

### ISSUE THREAD

**Issue by Krajiyah** [ParsePlatform/parse-server-example#84]
I am running latest release of node (around v5) on Ubuntu Desktop. I have cloned parse-server-example, and ran sudo npm install....but when I run "node index.js" I get a node error saying it cant find parse-server! I looked inside node_modules directory and I can see the parse-server files are there. Also "npm ls" acknowledges that parse-server@2.1.3 is installed.

**Comment by abhilash2in** [comment]
try sudo npm install, followed by npm start

**Comment by timwekken** [comment]
I'm having this same issue. It works fine for parse-server version 2.1.2, but when I try to update to 2.13 or 2.1.4 I get this error.

**Comment by drew-gross** [comment]
Have you run `npm install`?

**Comment by Krajiyah** [comment]
never mind was issue with not using latest node and npm
