### ISSUE TITLE
Unable to launch server on local machine

### ISSUE THREAD

**Issue by Sepho** [ParsePlatform/parse-server-example#9]
I've followed this steps in order to be able to run example on my local machine (mac-os).

* Make sure you have at least Node 4.1. `node --version`
* Clone this repo and change directory to it.
* `npm install`
* Install mongo locally using http://docs.mongodb.org/master/tutorial/install-mongodb-on-os-x/
* Run `mongo` to connect to your database, just to make sure it's working. Once you see a mongo prompt, exit with Control-D
* Run the server with: `npm start`

I've mongod running and mongo launches mongo console. However I got this error when I executes both `npm start` and `node index.js`:

> $ npm start

> parse-server-example@1.0.0 start /Users/javiercancio/parse/parse-server-example
> node index.js

> DATABASE_URI not specified, falling back to localhost.
> /Users/javiercancio/parse/parse-server-example/node_modules/bindings/bindings.js:83
>        throw e
>        ^
>
>Error: Module did not self-register.
>    at Error (native)
>   at Object.Module._extensions..node (module.js:435:18)
>  at Module.load (module.js:344:32)
>    at Function.Module._load (module.js:301:12)
>    at Module.require (module.js:354:17)
>    at require (internal/module.js:12:17)
>    at bindings (/Users/javiercancio/parse/parse-server->example/node_modules/bindings/bindings.js:76:44)
>    at Object.<anonymous> (/Users/javiercancio/parse/parse-server->example/node_modules/bcrypt/bcrypt.js:3:35)
>    at Module._compile (module.js:410:26)
>   at Object.Module._extensions..js (module.js:417:10)
>
>npm ERR! Darwin 14.5.0
>npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
>npm ERR! node v4.2.6
>npm ERR! npm  v2.14.12
>npm ERR! code ELIFECYCLE
>npm ERR! parse-server-example@1.0.0 start: `node index.js`
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the parse-server-example@1.0.0 start script 'node index.js'.
>npm ERR! This is most likely a problem with the parse-server-example package,
>npm ERR! not with npm itself.
>npm ERR! Tell the author that this fails on your system:
>npm ERR!     node index.js
>npm ERR! You can get their info via:
>npm ERR!     npm owner ls parse-server-example
>npm ERR! There is likely additional logging output above.
>
>npm ERR! Please include the following file with any support request:
>npm ERR!     /Users/javiercancio/parse/parse-server-example/npm-debug.log

**Comment by ranhsd** [comment]
same here.. i also get the same error above..

**Comment by billymwlei** [comment]
in index.js 
there is a line:
if (!process.env.DATABASE_URI) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
}

set the env variable before you launch

**Comment by mfkenson** [comment]
@billymwlei It also works even I did not set the env var. It would use default connection string.
`  databaseURI: process.env.DATABASE_URI || 'mongodb://localhost:27017/dev',`

**Comment by billymwlei** [comment]
Solved.....

In my case , I use node 0.12 perviously and npm install
so

Step 1, remove node_module folder,
Step 2, use nvm to change to latest node version -> nvm install 5.0 | nvm use 5.0
Step 3, npm install

Done!!!
Happy Coding.
