### ISSUE TITLE
How to update parse-server?

### ISSUE THREAD

**Issue by benc555** [ParsePlatform/parse-server-example#90]
Getting the following issue when trying to interact with Parse--just deployed to Heroku.

[Error]: {"code":1,"message":"Internal server error."} (Code: 1, Version: 1.12.0)
ERROR 1: Error Domain=Parse Code=1 "{"code":1,"message":"Internal server error."}" UserInfo={error={"code":1,"message":"Internal server error."}, NSLocalizedDescription={"code":1,"message":"Internal server error."}, code=1} [error: {"code":1,"message":"Internal server error."}, NSLocalizedDescription: {"code":1,"message":"Internal server error."}, code: 1]

Anyone know why this is happening and how to fix it?

**Comment by benc555** [comment]
I saw @40 but not helpful

**Comment by threegoblins** [comment]
I’m basically in the same place but one step forward maybe. 
That error for me was because the app can’t connect to the DB. I’m using ObjectRocket which needs the IP address whitelisted.

I worked that out by checking $ heroku logs —tail

So now I have added “Fixie” to Heroku so that I can get a static IP, but that still doesn’t solve it because I need to make the parse-server-example app actually use the proxy of Fixie.

And that isn’t turning out to be as simple as it sounds, at least for me (this is my first node experience :)).

Hope that helps!

**Comment by benc555** [comment]
@threegoblins so, to confirm, your MongoDB is not hosted through Heroku?

**Comment by threegoblins** [comment]
Correct, hosted by ObjectRocket.
Although I am kinda regretting that as a Heroku hosting probably would have been simpler… 

You’re hosted with Heroku? Hopefully you won’t be having the same error then.

But either way checking your app logs on Heroku should reveal more information for you as to why the 500 is happening.

**Comment by occurrentarts** [comment]
perhaps to update, pull the latest .zip of parse-server from the github and replace it with the parse-server folder in node_modules.

not 100% if this is correct.

**Comment by occurrentarts** [comment]
npm update parse-server might also work, but it filled my node_modules folder with a ton of other stuff too.

**Comment by drew-gross** [comment]
I'd recommend editing your `package.json` file and updating the `parse-server` entry, then running `npm install`. If you are hosting on Heroku, the `npm install` should happen when you `git push` to your server.

**Comment by w3care25** [comment]
I am getting following error when trying to requestPasswordReset. 
My Parse server version is : 1.0.0
`{"level":"error","message":"Uncaught internal server error. [TypeError: promiseHandler(...).then is not a function] TypeError: promiseHandler(...).then is not a function\n    at parse/node_modules/parse-server/lib/PromiseRouter.js:286:27\n `


also email is not going.
