### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by abhilash2in** [ParsePlatform/parse-server-example#93]
I've deployed parse-server-example on an amazon EC2 instance. Everything was working fine for a while (so it has been set up properly) but suddenly after updating `parse-server` version, I'm getting `502 Bad Gateway` response for every request being made. Unable to figure out the reason

Here is my package.json
```
{
  "name": "parse-server-example",
  "version": "1.0.0",
  "description": "An example Parse API server using the parse-server module",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/ParsePlatform/parse-server-example"
  },
  "license": "MIT",
  "dependencies": {
    "express": "~4.2.x",
    "kerberos": "~0.0.x",
    "parse": "~1.6.12",
    "parse-server": "~2.1.4"
  },
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": ">=4.3"
  }
}
```

**Comment by drew-gross** [comment]
Bad gateway usually indicates a problem with your load balancer or proxy or firewall or something else that sits in between Parse Server and your client.

**Comment by abhilash2in** [comment]
Logs said `You must provide a serverURL!` and suddenly I see a new environment variable being required for the same. This wasn't the case a while ago when I'd deployed

**Comment by abhilash2in** [comment]
I updated `parse-server-example` and specified serverURL enviroment variable. It is working fine now. Can I also update 'parse-server' to '2.1.4'?

**Comment by drew-gross** [comment]
Sure! Make sure you test it before deploying, especially is you use `S3Adapter`. Some people have been having issues with certain configurations of the `S3Adapter`.
