### ISSUE TITLE
Add Parse Dashboard to the example

### ISSUE THREAD

**Issue by christianmarth** [ParsePlatform/parse-server-example#94]
It would be nice to add the dashboard to this example

**Comment by gfosco** [comment]
I think we should link to it, but right now it's best to run the dashboard locally.

**Comment by tommyrice** [comment]
+1

**Comment by drew-gross** [comment]
The dashboard is now available on `npm` so this would be much easier to add.

**Comment by thamer898** [comment]
Hello @drew-gross 

Can you help me please to configure reset user password with parse Version 2.1.6 ?

Regards
