### ISSUE TITLE
AWS Deploy Button is not the latest version.

### ISSUE THREAD

**Issue by pushtek** [ParsePlatform/parse-server-example#97]
Is there a way to get parse on aws with the latest version?

**Comment by drew-gross** [comment]
Yes you need to clone the project, update the parse server version in package.json, then push the project.

**Comment by pushtek** [comment]
I always get a 502 Bad Gateway error. I use the "Upload and Deploy" Button. Is that right

**Comment by drew-gross** [comment]
I'm not familiar with the details of AWS, sorry. That sounds like an AWS specific problem.

**Comment by Controlhaus** [comment]
I got around this by first using the AWS button, then cloning the project, then deploying the cloned project to the AWS application created with the button.

**Comment by greggmojica** [comment]
Does this fix still work @Controlhaus?

**Comment by Controlhaus** [comment]
I haven't used it since March, but it won't hurt to just try it and see what happens.
Good luck!
