### ISSUE TITLE
How to login Twitter ({"code":1,"message":"Internal server error."} (Code: 1, Version: 1.12.0)

### ISSUE THREAD

**Issue by kenjiIdo** [ParsePlatform/parse-server-example#98]
Hello Dears, 
please help me.
I found the console log message when i login with Twitter using PFLoginViewController.
[Error]:{"code":1,"message":"Internal server error."} (Code: 1, Version: 1.12.0)
also i get the "Login Failed" alert message.
but it's OK when i login with other login method.
Only can't twitter login.

 -------  package.json file "parse-server": "~2.1.4" --------

1. ----- Heroku log --------
at validateAuthData (/app/node_modules/parse-server/lib/oauth/twitter.js:9:16)
at new OAuth (/app/node_modules/parse-server/lib/oauth/OAuth1Client.js:7:30)
at RestWrite.handleOAuthAuthData (/app/node_modules/parse-server/lib/RestWrite.js:331:10)
at process._tickDomainCallback (node.js:425:11)
at _combinedTickCallback (node.js:370:9)
Uncaught internal server error. [TypeError: Cannot read property 'consumer_key' of undefined] TypeError: Cannot read property 'consumer_key' of undefined
--------------------------

 2. ------ I typed consumer_key correctly in Appdelegate -------------

ParseClientConfiguration *parseConfiguration = [ParseClientConfiguration configurationWithBlock:^(id _Nonnull configuration) {
[configuration setApplicationId:@"AppId_xxxxxxxxxx"];
[configuration setClientKey:@"AppMasterKey_xxxxxxxxxx"];
[configuration setServer:@"https://xxxxxxxapi.herokuapp.com/parse"];
}];

[Parse initializeWithConfiguration:parseConfiguration];

[PFTwitterUtils initializeWithConsumerKey:@"Ekxxxxxxxxxxxxxx" consumerSecret:@"mexxxxxxxxxxxxxxxxxxxxxxxx"];
---------------

please help me

**Comment by kenjiIdo** [comment]
ParseClientConfiguration *parseConfiguration = [ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration>  _Nonnull configuration) {
        [configuration setApplicationId:@"AppId_xxxxxxxxxx"];
        [configuration setClientKey:@"AppMasterKey_xxxxxxxxxx"];
        [configuration setServer:@"https://xxxxxxxapi.herokuapp.com/parse"];
    }];

[Parse initializeWithConfiguration:parseConfiguration];
   
[PFTwitterUtils initializeWithConsumerKey:@"Ekxxxxxxxxxxxxxx"                               consumerSecret:@"mexxxxxxxxxxxxxxxxxxxxxxxx"];

please help me

**Comment by yoshiboarder** [comment]
How to solve this problem?
